version: "3"
services:
  late_classification:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    network_mode: host
    # restart: "always"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_PORT=5432
      - DB_NAME=test
      - CONSUMER_TOPICS=features
      - CONSUMER_SERVER=localhost:9092
      - CONSUMER_GROUP_ID=late_steps
      - PRODUCER_TOPIC=late_classification
      - PRODUCER_SERVER=localhost:9092
      - ES_PREFIX=ztf_pipeline
      - ES_NETWORK_HOST=localhost
      - ES_NETWORK_PORT=9200
      - LOGGING_DEBUG=True
      - CLASSIFIER_NAME=late
      - TAXONOMY_NAME=v1